backend/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import urlpatterns as urls, i18n_patterns
from django.http.response import HttpResponseRedirect
from django.utils.translation import activate
from django.views.static import serve


urlpatterns = urls

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
)


def change_lang(req):
    try:
        now_lang = req.session.get('django_language', None) or req.COOKIES.get('django_language', 'uz')
    except:
        now_lang = 'uz'
    
    if now_lang == 'uz':
        new_lang = 'en'
    else:
        new_lang = 'uz'
    
    req.session['django_language'] = new_lang
    activate(new_lang)

    res = HttpResponseRedirect(f'/{new_lang}')
    res.set_cookie('django_language', new_lang)

    return res


# urlpatterns.append(path('change-lang', change_lang))
# urlpatterns.append(path('', lambda request: HttpResponseRedirect('/uz')))


main/urls.py
from django.urls import path
from .views import IndexView, ListNews, ListGallary, NewsView, GallaryView,accept_murojaat,ChangeLenguage

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('chl', ChangeLenguage.as_view()),
    path('news/', ListNews.as_view(), name='list_news'),
    path('send-murojaat/', accept_murojaat, name='accept-murojaat'),
    path('gallary/', ListGallary.as_view(), name='list_gallary'),
    path('news/<str:slug>/', NewsView.as_view(), name='news_detail'),
    path('gallary/<int:pk>/', GallaryView.as_view(), name='gallary_detail'),
]

main/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class About(models.Model):
    title = models.CharField(max_length=256)
    text = models.TextField()
    tizer = models.CharField(max_length=256)

    class Meta:
        verbose_name = "Biz haqimizda"
        verbose_name_plural = "Biz haqimizda maqolalar"

    def __str__(self) -> str:
        return self.title

class News(models.Model):
    image = models.ImageField(upload_to='images/%Y.%m.%d/news/')
    title = models.CharField(max_length=256)
    date = models.DateField()
    text = models.TextField()
    big_text = RichTextField()
    slug = models.SlugField()

    class Meta:
        verbose_name = "Yangilik"
        verbose_name_plural = "Yangiliklar"

    def __str__(self) -> str:
        return self.title

class Plans(models.Model):
    image = models.ImageField(upload_to='images/%Y.%m.%d/plans/')
    title = models.CharField(max_length=256)
    text = models.TextField()
    data = models.DateField()

    class Meta:
        verbose_name = "Kelgusi tadbir"
        verbose_name_plural = "Kelgusi tadbirlar"

    def __str__(self) -> str:
        return self.title


class TeamMember(models.Model):
    image = models.ImageField(upload_to="images/%Y.%m.%d/team/")
    name = models.CharField(max_length=256)
    profession = models.CharField(max_length=256)
    text = models.TextField()

    class Meta:
        verbose_name = "Jamoa azosi"
        verbose_name_plural = "Jasmoa azolari"

    def __str__(self) -> str:
        return self.name


class Gallary(models.Model):
    image = models.ImageField(upload_to='images/%Y.%m.%d/gallary/')

    class Meta:
        verbose_name = "Galareya surati"
        verbose_name_plural = "Galareya suratlari"

    def __str__(self) -> str:
        return str(self.pk)


class Partner(models.Model):
    image = models.ImageField(upload_to='images/%Y.%m.%d/partner/')

    class Meta:
        verbose_name = "Hamkor"
        verbose_name_plural = "Hamkorlar"

    def __str__(self) -> str:
        return f"{self.pk}inchi hamkor"


class Map(models.Model):
    embeded_url = models.CharField(max_length=256)

    class Meta:
        verbose_name = "Xarita"
        verbose_name_plural = "Xaritalar"

    def __str__(self) -> str:
        return f"{self.pk}inchi hamkor"

class Murojaat(models.Model):
    ism = models.CharField(max_length=150)
    email = models.CharField(max_length=150)
    phone = models.CharField(max_length=150)
    matn = models.TextField()

main/forms.py
from django import forms
from .models import Murojaat


class MurojaatForm(forms.ModelForm):
    class Meta:
        model = Murojaat
        fields = ("ism","email","phone","matn")

main/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.views.generic import *
from .models import *
from .forms import MurojaatForm
# Create your views here.


DEFAULT_ABOUT = {
    "title": "O'zbekistonda eng katta IT jamiyat",
    "text": "Digital Generation Uzbekistan NNM ning asosiy vazifasi yoshlarni bilim va ilmga chorlash, axborot, texnologiyalari soxasida ayollarni o'rnini ko'paytirish, yoshlarni mamlakatda amalga oshirilayotgan axborot kommunikatsiya islohotlarini chuqurlashtirishda faol ishtirok etishga jalb qilish.",
    "tizer": "https://www.youtube.com/watch?v=GkD7frg0nLk"
}

DEFAULT_MAP = {
    'embeded': "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1059.2053788673786!2d69.21860131180253!3d41.33310910350248!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2s!4v1706543496574!5m2!1sru!2s"
}

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['about'] = list(About.objects.all() or [DEFAULT_ABOUT])[0]
        context['news'] = list(News.objects.order_by('-date'))[:4]
        context['future'] = list(Plans.objects.order_by('-data'))[:4]
        context['team'] = list(TeamMember.objects.all())

        gallary = Gallary.objects.all()

        context['gallary_row_1'] = gallary[0:3]
        context['gallary_row_2'] = gallary[3:6]
        context['latest_gallary'] = Gallary.objects.all().order_by('-id')[:3]
        context['partners'] = Partner.objects.all()
        context['map'] = Map.objects.first() or DEFAULT_MAP
        return context


class ListNews(ListView):
    paginate_by = 16
    template_name = 'list-news.html'
    model = News


class ListGallary(ListView):
    paginate_by = 16
    template_name = 'list-gallary.html'
    model = Gallary
    def get_queryset(self):
        return Gallary.objects.all().order_by('-id')
class NewsView(DetailView):
    template_name = 'new.html'
    model = News


class GallaryView(DetailView):
    template_name = 'gallary.html'
    model = Gallary
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_gallary'] = Gallary.objects.all().order_by('-id')[:3]
        return context

def accept_murojaat(request):
    if request.method == "POST":
        form = MurojaatForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    return redirect('/')



class ChangeLenguage(View):
    def get(self, request):
        return redirect(f'/{request.GET.get("lng", "ru")}')

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Digital Generation - {% block title %}Asosiy sahifa{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css">
    <meta name="title" content="Digital Generation Uzbeksitan">
    <meta name="description"
        content="O'zbekiston Yoshlarini Raqamli Avlodga bo'lgan qiziqshlarini, ularni xarakatlarini rag'batlantirishga yo'naltirilgan nodavlat notijorat muassasa.">
    <meta name="keywords"
        content="digitalgeneration, digita, digital uzbekistan, digital generation uzbekistan, digitalgeneration, digitalgenerationuzbekistan. dguzbekistan, raqamliavlod, raqamli avlod, raqamli avlod it oromgohi, it, it uzbekistan, digita camp">
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">
    <meta name="author" content="Digital Generation Uzbeksitan NNM">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="manifest" href="/static/img/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <script src="/static/playerjs.js" type="text/javascript"></script>

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-white">
            <div class="container style-container">
                <a class="navbar-brand" href="#">
                    <img src="/static/img/logo.png" alt="Bootstrap" height="60">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse align-items-center justify-content-center w-100"
                    id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center justify-content-center w-100">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">{% trans "home" %}</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/#news">{% trans "news" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/#in-future">{% trans "events" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/#our-team">{% trans "our_team" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/#contact">{% trans "contact_us" %}</a>
                        </li>
                        
                    </ul>
                    <div class="another-content d-flex align-items-center" style="gap: 2rem">
                        <ul class="nav nav-pills">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                                    aria-expanded="false">{% trans "languages" %}</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{{ request.cookies.django_language }}/uz/">Uzb</a></li>
                                    <li><a class="dropdown-item" href="{{ request.cookies.django_language }}/en/">Eng</a></li>
                                    <li><a class="dropdown-item" href="{{ request.cookies.django_language }}/ru/">Rus</a></li>
                                </ul>
                            </li>
                        </ul>
                        <a class="btn btn-success p-0 px-4 d-flex align-items-center justify-content-center rounded-3 border-0"
                            style="background-color: #5FB465;height: 40px;width: max-content;" id="video-darslik"
                            href="https://raqamliavlod.uz/courses">
                            <img src="/static/img/svg/video.svg" alt="" width="22" height="14">
                            
                            <div class="ms-2 w-100">{% trans 'video_lesson' %}</div>
                        </a>
                        <!-- <div class="split" style="height: 38px;border-left: 1px solid #C4C4C4;"></div>
                        <div class="lang d-flex" onclick="window.location = '/change-lang?furl={{ request.path }}'">
                            <div class="flag">
                                <span style="background-color: #66C9F3;"></span>
                                <span style="background-color: #F9F9F9;"></span>
                                <span style="background-color: #5FC047;"></span>
                            </div>
                            <span class="ms-2">{% if request.session.django_language == 'uz' %}{% trans 'eng' %}{% else %}{% trans 'uz'%}{% endif %}</span>
                    </ul>
                    <div class="another-content d-flex align-items-center" style="gap: 2rem">
                        <a class="btn btn-success p-0 px-4 d-flex align-items-center justify-content-center rounded-3 border-0" style="background-color: #5FB465;height: 40px;width: max-content;" id="video-darslik" href="https://raqamliavlod.uz/courses">
                            <img src="/static/img/svg/video.svg" alt="" width="22" height="14">
                            <div class="ms-2 w-100">{% trans 'video_lesson' %}</div>
                        </a>
                        <!-- <div class="split" style="height: 38px;border-left: 1px solid #C4C4C4;"></div>
                        <div class="lang d-flex" onclick="window.location = '/change-lang?furl={{ request.path }}'">
                            <div class="flag">
                                <span style="background-color: #66C9F3;"></span>
                                <span style="background-color: #F9F9F9;"></span>
                                <span style="background-color: #5FC047;"></span>
                            </div>
                            <span class="ms-2">{% if request.session.django_language == 'uz' %}{% trans 'eng' %}{% else %}{% trans 'uz'%}{% endif %}</span>
                        </div> -->
                    </div>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}{% endblock content %}

    <footer>
        <div class="color-bars">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
        <div class="footer-data">
            <div class="row g-0 h-100">
                <div class="col">
                    <img src="/static/img/logo-white.png" alt="" height="60">
                </div>
                <div class="col">
                    <p class="m-0 copyright">Digital Generation Uzbekistan © 2023</p>
                </div>
                <div class="col">
                    <div class="collection">
                        <a href="http://facebook.com/digitalgeneration.uz">
                            <img src="/static/img/Fill 3.svg" alt="" width="15px" height="15px">
                        </a>
                        <a href="http://instagram.com/dguzbekistan">
                            <img src="/static/img/Fill 23.svg" alt="" width="15px" height="15px">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script>
        var player = new Playerjs({ id: "player", file: "/static/video.mp4" });
    </script>
    <script>
        const lightbox = GLightbox({
            selector: '.glightbox',
            type: 'video',
            youtube: {
                autoplay: 1
            }
        });

        const lightbox2 = GLightbox({
            selector: '.glightbox-im',
            type: 'image',
        });

        $('#contact-form').submit((event) => {
            let name = $('#contact_name').val();
            let email = $('#contact_email').val();
            let phone = $('#contact_phone').val();
            let text = $('#contact_text').val();

            if (name && email && phone && text) {
                let fullMessage = `<b>${email}</b> ${phone}\n\n<i>${name}</i>\n-----------------\n${text}`;

                $.ajax({
                    url: "https://api.telegram.org/bot5918813660:AAFw1s57GVFP3FC_Mpvdt8AQ_xb5YbvxYDY/sendMessage",
                    dataType: 'JSON',
                    method: 'POST',
                    data: {
                        chat_id: '5599197669',
                        text: fullMessage,
                        parse_mode: 'HTML'
                    },
                    success: data => {

templates/gallary.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<style>
    .row {
        display: flex;
        flex-wrap: wrap !Important;
        justify-content: center !Important;
    }
</style>
<section style="min-height: 100vh;">
    <div class="container py-5">
        <div class="row g-3">
        <div>
    </div>
</section>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Asosiy sahifa{% endblock title %}
{% load i18n %}
{% block content %}
    <style>
	.team-member h4 {
		height:unset !Important;
	}
    </style>
    <section id="hero">
        <div class="row g-0">
            <div class="col-lg-5 col-md-5 col-sm-12">
                <div id="left-hero">
                    <div class="vector"></div>
                    <div class="content">
                        <h4>Digital Generation Uzbekistan</h4>
                        <h1><span>{% trans "IT dunyosini" %}</span><br>
                            {% trans "biz bilan kashf eting" %}</h1>
                        <a href="#about-us" class="btn btn-success rounded-3">{% trans 'more' %}</a>
                    </div>
                    <div class="gradient"></div>
                </div>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-12">
                <div id="right-hero"></div>
            </div>
        </div>
    </section>

    <div id="about-us">
        <div class="vector"></div>
        <div class="vector"></div>
        <div class="container style">
            <div class="row">
                <div class="col-lg-4 d-flex align-items-center justify-content-left">
                    <img src="/static/img/logo-about.png" alt="">
                    <h3>{% trans 'about_us' %}</h3>
                </div>
                <div class="col-md-8">
                    <h4>{% trans 'biggest_it_company_in_uzbekistan' %}</h4>
                    <p>{% trans 'about_us_text' %}</p>
                </div>
                <hr id="sep">
            </div>
        </div>
    </div>

    <div id="about-vidoe-container">
<iframe width="560" height="315" src="https://www.youtube.com/embed/YMh5eatynV8?si=UryvZ_wVcPHeyHFC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
<!-- <video tabindex="-1" class="video-stream html5-main-video" webkit-playsinline="" playsinline="" controlslist="nodownload" style="width: 1176px; height: 662px; left: 0px; top: 0px;" src="https://www.youtube.com/watch?v=YMh5eatynV8&list=PLR4Kn3MQZTc8XyLT8RJuet7eF6xMU57LJ"></video> -->
        <!-- <div class="player">
            <a href="https://www.youtube.com/watch?v=YMh5eatynV8&list=PLR4Kn3MQZTc8XyLT8RJuet7eF6xMU57LJ" class="glightbox">
                <div class="play-button">
                    <img src="/static/img/play-button.png" alt="">
                </div>
            </a> -->
          <!--  <div class="text">{% trans 'say_tizer_video' %}</div>
            <div id="player"></div> -->

    </div>

    <div id="news">
        <div class="container py-5">
            <div class="title">
                <div class="text">{% trans 'news' %}</div>
                <a href="{% url 'main:list_news' %}" class="link">{% trans 'all_details' %}</a>
            </div>

            <div class="content">
                <div class="row g-4">
                    {% for new in news %}
                    <div class="col-lg-3 col-md-3 col-sm-12">
                        <div class="card news-card border-0 h-100 rounded-3" style="overflow: hidden;">
                            <img src="{{ new.image.url }}" alt="" class="card-image-top">
                            <div class="card-body">
                                <h3 class="mb-3">{{ new.title }}</h3>
                                <p class="mb-3 small">{{ new.date|date:"d F, Y" }}</p>
                                <p class="m-0">{{ new.text }}</p>
                            </div>
                            <div class="card-footer bg-white"><a href="{% url 'main:news_detail' new.slug %}" class="btn btn-outline-primary w-100 rounded-3" style="border-width: 2px;">{% trans 'more' %}</a></div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div id="in-future">
        <div class="container py-5">
            <div class="title">{% trans "Tadbirlarimiz" %}
            </div>

            <div class="future-cards">
                {% for plan in future %}
                <div class="future-card" style="--color: #3D67AD;">
                    <div class="time-data">
                        <div class="line"></div>
                        <div class="dot"></div>
                        <div class="time">{{ plan.data|date:"d F," }}<br>
                            {{ plan.data.year }} {% trans "year" %}</div>
                    </div>
                    <div class="text-data">
                        <img src="{{ plan.image.url }}" alt="" class="image">
                        <div class="content">
                            <h3>{{ plan.title }}</h3>
                            <div class="line"></div>
                            <p>{{ plan.text }}</p>

                            <span class="datetime">{{ plan.data|date:"d F," }} {{ plan.data.year }} yil</span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div id="our-team">
        <div class="container py-5">
            <div class="title">{% trans 'our_team' %}</div>
	    <div class="row g-4 justify-content-evenly">
		<div class="team-member col-lg-3 col-md-3 col-sm-12" >
			<img src="/static/img/djalalov.jpeg" alt="..." style="border: none; border-radius: 50%;" loading="lazy">
                	<h4>Djalalov Azamat Axrarovich</h4>
                	<small>Direktor</small>
		</div>
		<div class="team-member col-lg-3 col-md-3 col-sm-12" >
                        <img src="/static/img/miromon.png" alt="..." style="border: none; border-radius: 50%;" loading="lazy" >
                        <h4>Tursunov Miromon Oybekovich</h4>
                        <small>Loyiha Koordinatori</small>
                </div>
		<div class="team-member col-lg-3 col-md-3 col-sm-12" >
                        <img src="/static/img/muzaffarka.png" alt="..." style="border: none; border-radius: 50%;"  loading="lazy">
                        <h4>Musashayxov Muzaffar</h4>
                        <small>Maslahatchi</small>
                </div>
		<!-- <div class="team-member col-lg-3 col-md-3 col-sm-12" >
                        <img src="/static/img/maloxat.jpg" alt="..." style="border: none; border-radius: 50%" loading="lazy">
                        <h4>Shahobiddinova Malohat Zaynilobiddin qizi</h4>
                        <small>DG Ladies loyiha koordinatori</small>
                </div> -->
	    </div>
	<br />
	<br/>
            <div class="team-members row g-4">
                {% for member in team %}
                <div class="team-member col-lg-3 col-md-3 col-sm-12">
                    <img src="{{ member.image.url }}" alt="..." loading="lazy" >
                    <h4>{{ member.name }}</h4>
                    <small>{{ member.profession }}</small>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div id="gallary">
        <div class="container py-5">
            <div class="title">
                <span>{% trans 'gallary' %}</span>
                <a href="{% url 'main:list_gallary' %}">{% trans 'all' %}</a>
            </div>
            <div class="gallary">
		    <div class="row__gallary">
                    {% for gallary in latest_gallary %}
                    <img src="{{ gallary.image.url }}" alt="" class="glightbox-im image">
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>

    <div id="partners">
        <div class="container">
            <div class="title">{% trans "Hamkorlarimiz" %}</div>
        </div>

        <div class="my-slides">
            <div>
		<swiper-container 
  loop="true" 
  autoplay-delay="2500" 
  autoplay-disable-on-interaction="false" 
  space-between="10" 
  slides-per-view="4" 
  centered-slides="false"
  breakpoints='{
    "300": { "slidesPerView": 1, "spaceBetween": 10, "centeredSlides": true },
    "768": { "slidesPerView": 2, "spaceBetween": 10 },
    "1024": { "slidesPerView": 3, "spaceBetween": 10 },
    "1366": { "slidesPerView": 4, "spaceBetween": 10 }
  }'
>
  {% for partner in partners %}
    <swiper-slide>
      <img src="{{ partner.image.url }}" alt="" height="98px">
    </swiper-slide>
  {% endfor %}
</swiper-container>

<script>
  window.addEventListener('resize', () => {
    const swiper = document.querySelector('swiper-container');
    swiper.swiper.update(); // Manually trigger update on resize
  });
</script>

	    </div>
	</div>
    </div>

    <div id="contact">
        <div class="container">
            <div class="form">
                <div class="row g-0">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <form action="{% url 'main:accept-murojaat' %}" method="post" id="contact-form">
                            <p class="m-0">{% trans "Takliflar va murojaat uchun" %}</p>
                            <h3>{% trans "qayta aloqa" %}</h3>
                            <div class="row g-4">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <label for="" class="form-label">{% trans "name" %}</label>
                                    <input type="text" name="ism" class="form-control" id="contact_name">
                                    <div class="error"></div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <label for="" class="form-label">{% trans "email" %}</label>
                                    <input type="text" name="email" class="form-control" id="contact_email">
                                    <div class="error"></div>
                                </div>
                                <div class="col-12">
                                    <label for="" class="form-label">{% trans "phone_number" %}</label>
                                    <input type="text" name="phone" class="form-control" id="contact_phone">
                                    <div class="error"></div>
                                </div>
                                <div class="col-12">
                                    <label for="" class="form-label">{% trans "text" %}</label>
                                    <textarea id="contact_text" name="matn" rows="5" class="form-control"></textarea>
                                    <div class="error"></div>
                                </div>
                                <div class="col-12" style="text-align: right;">
                                    <button class="btn btn-primary">{% trans "send" %}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <iframe src="{{ map.embeded }}" width="100%" height="675px" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/list-news.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<section style="min-height: 100vh;">
    <div class="container py-5">
        <div class="row g-4">
            {% for new in page_obj.object_list %}
            <div class="col-lg-3 col-md-3 col-sm-12">
                <div class="card news-card border-0 h-100 rounded-3" style="overflow: hidden;">
                    <img src="{{ new.image.url }}" alt="" class="card-image-top">
                    <div class="card-body">
                        <h3 class="mb-3">{{ new.title }}</h3>
                        <p class="mb-3 small">{{ new.date|date:"d F, Y" }}</p>
                        <p class="m-0">{{ new.text }}</p>
                    </div>
                    <div class="card-footer bg-white"><a href="{% url 'main:news_detail' new.slug %}" class="btn btn-outline-primary w-100 rounded-3" style="border-width: 2px;">{% trans 'more' %}</a></div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="py-5 w-100">
            <ul class="pagination w-100 align-items-center justify-content-center">
                <li class="page-item">
                    {% if page_obj.has_previous %}
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{% trans 'prev' %}</a>
                    {% else %}
                    <a class="page-link disabled" href="#">{% trans 'prev' %}</a>
                    {% endif %}
                </li>

                {% for i in page_obj.paginator.page_range %}
                <li class="page-item"><a class="page-link {% if page_obj.number == i %}active{% endif %}" href="?page={{ i }}">{{ i }}</a></li>
                {% endfor %}

                <li class="page-item">
                    {% if page_obj.has_next %}
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'next' %}</a>
                    {% else %}
                    <a class="page-link disabled" href="#">{% trans 'next' %}</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</section>
{% endblock content %}